services:
  rails:
    image: sfr2077
    environment:
      RAILS_ENV: development
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command:
      - 'bin/rails'
      - 'server'
      - '-b'
      - '0.0.0.0'
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: sfr2077
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
volumes:
  .:
