services:
  initialization:
    image: node:21
    working_dir: /rails
    volumes:
      - .:/rails
    command:
      - 'npm'
      - 'install'
  node:
    image: node:21
    working_dir: /rails
    volumes:
      - .:/rails
    command:
      - 'npm'
      - 'start'
    depends_on:
      - initialization
  rails:
    image: sfr2077
    environment:
      RAILS_ENV: development
      RAILS_DEVELOPMENT_HOSTS: atreyu
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - node
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: sfr2077
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
volumes:
  .:
