# Use the official Ruby image as the base image
FROM ruby:latest

# Set the working directory inside the container
WORKDIR /app

# Install system dependencies
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs npm

# Copy Gemfile and Gemfile.lock into the container
COPY Gemfile Gemfile.lock ./

# Install Ruby dependencies
RUN gem install bundler
RUN bundle install

# Bootstrap project
RUN gem install rails 
RUN rails new sfr2077 --webpack=react --database=postgresql

# Seed database
RUN rails generate model Protein name:string
RUN rails generate model Vegetable name:string
RUN rails generate model Seasoning name:string
RUN rails db:migrate

# Copy the rest of the application code into the container
COPY . .

# Expose port 3000 to the outside world
EXPOSE 3000

# Start the Rails application
CMD ["rails", "server", "-b", "0.0.0.0"]
